/**
 * Brazilian Portuguese search words for common Lucide icons, matched like
 * Lucide's own English tags. Keys must be Lucide icon names (a unit spec
 * checks them against the installed lucide-static).
 */
export const PT_BR_SYNONYMS: Record<string, string[]> = {
  'alarm-clock': ['despertador', 'alarme'],
  baby: ['bebê', 'criança'],
  banknote: ['dinheiro', 'nota', 'pagamento'],
  bell: ['sino', 'notificação', 'aviso'],
  bike: ['bicicleta', 'bike', 'ciclismo'],
  book: ['livro', 'leitura'],
  'book-open': ['livro aberto', 'leitura', 'estudo'],
  bookmark: ['marcador', 'favorito', 'salvar'],
  brain: ['cérebro', 'mente', 'pensamento'],
  briefcase: ['maleta', 'trabalho', 'emprego'],
  bus: ['ônibus', 'transporte'],
  cake: ['bolo', 'aniversário'],
  calendar: ['calendário', 'data', 'agenda'],
  'calendar-days': ['calendário', 'dias', 'agenda'],
  camera: ['câmera', 'foto'],
  car: ['carro', 'automóvel'],
  cat: ['gato'],
  'chart-line': ['gráfico', 'linha', 'tendência'],
  'chart-pie': ['gráfico', 'pizza'],
  check: ['ok', 'feito', 'concluído', 'certo', 'confirmar'],
  'circle-question-mark': ['ajuda', 'dúvida', 'pergunta'],
  clock: ['relógio', 'hora', 'tempo'],
  cloud: ['nuvem'],
  code: ['código', 'programação'],
  coffee: ['café', 'pausa'],
  compass: ['bússola', 'direção'],
  dog: ['cachorro', 'cão'],
  'dollar-sign': ['dinheiro', 'dólar', 'preço'],
  download: ['baixar', 'download'],
  dumbbell: ['academia', 'exercício', 'treino'],
  euro: ['euro', 'dinheiro'],
  eye: ['olho', 'ver', 'visualizar'],
  'face-slightly-smiling': ['sorriso', 'feliz', 'carinha'],
  file: ['arquivo', 'documento'],
  flag: ['bandeira', 'marco'],
  flame: ['fogo', 'chama', 'quente'],
  folder: ['pasta', 'diretório'],
  gift: ['presente', 'brinde'],
  globe: ['mundo', 'globo', 'internet'],
  'graduation-cap': ['formatura', 'estudo', 'faculdade', 'escola'],
  hammer: ['martelo', 'ferramenta'],
  heart: ['coração', 'amor', 'curtir'],
  hourglass: ['ampulheta', 'espera'],
  house: ['casa', 'lar', 'início'],
  image: ['imagem', 'foto', 'figura'],
  info: ['informação', 'info'],
  key: ['chave', 'senha'],
  leaf: ['folha', 'natureza'],
  lightbulb: ['lâmpada', 'ideia'],
  link: ['link', 'ligação', 'vínculo'],
  'list-todo': ['tarefas', 'lista', 'afazeres'],
  lock: ['cadeado', 'bloqueado', 'trancado'],
  mail: ['e-mail', 'correio', 'carta'],
  map: ['mapa'],
  'map-pin': ['local', 'localização', 'endereço'],
  'message-circle': ['mensagem', 'conversa', 'comentário'],
  moon: ['lua', 'noite'],
  music: ['música', 'som'],
  'notebook-pen': ['caderno', 'anotações', 'diário'],
  'party-popper': ['festa', 'comemoração'],
  pencil: ['lápis', 'editar', 'escrever'],
  phone: ['telefone', 'ligação', 'celular'],
  pill: ['remédio', 'pílula', 'saúde'],
  pin: ['fixar', 'alfinete'],
  plane: ['avião', 'viagem', 'voo'],
  printer: ['impressora', 'imprimir'],
  rocket: ['foguete', 'lançamento'],
  search: ['buscar', 'pesquisar', 'lupa'],
  send: ['enviar'],
  settings: ['configurações', 'ajustes', 'engrenagem'],
  'shopping-cart': ['carrinho', 'compras', 'mercado'],
  sparkles: ['brilho', 'mágica', 'novidade'],
  'square-check': ['tarefa', 'feito', 'marcado'],
  star: ['estrela', 'favorito', 'destaque'],
  stethoscope: ['estetoscópio', 'médico', 'saúde'],
  sun: ['sol', 'dia', 'claro'],
  tag: ['etiqueta', 'rótulo'],
  target: ['alvo', 'meta', 'objetivo'],
  terminal: ['terminal', 'console'],
  'thumbs-up': ['joinha', 'curtir', 'aprovar'],
  'train-front': ['trem', 'metrô'],
  trash: ['lixeira', 'lixo', 'excluir', 'apagar'],
  'tree-pine': ['árvore', 'pinheiro', 'natal'],
  'triangle-alert': ['alerta', 'atenção', 'perigo'],
  trophy: ['troféu', 'conquista', 'prêmio'],
  umbrella: ['guarda-chuva', 'chuva'],
  upload: ['enviar', 'carregar'],
  user: ['usuário', 'pessoa', 'perfil'],
  users: ['usuários', 'pessoas', 'grupo', 'equipe'],
  utensils: ['talheres', 'comida', 'restaurante'],
  video: ['vídeo', 'filmagem'],
  wallet: ['carteira', 'finanças'],
  wrench: ['chave inglesa', 'ferramenta', 'conserto'],
  x: ['fechar', 'cancelar', 'erro'],
  zap: ['raio', 'energia', 'rápido']
}
